// Generated by Swift version 1.0 (swift-600.0.51.4)

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif
#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"

#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
@import UIKit;
@import CoreGraphics;
#endif

@class UITableView;
@class TableViewSection;
@class NSIndexPath;
@protocol TableViewDataSourceDelegate;

SWIFT_CLASS("_TtC12TableAdapter19TableViewDataSource")
@interface TableViewDataSource : NSObject <UITableViewDataSource, UITableViewDelegate>
@property (nonatomic, weak) IBOutlet UITableView * tableView;
@property (nonatomic, weak) id <TableViewDataSourceDelegate> delegate;
@property (nonatomic, readonly, copy) NSArray * sections;
@property (nonatomic, readonly) NSInteger numberOfSections;
- (NSArray *)dataSourceForIndexPath:(NSIndexPath *)indexPath;
- (TableViewSection *)tableSectionForIndexPath:(NSIndexPath *)indexPath;
- (TableViewSection *)tableSectionForIndex:(NSInteger)index;
- (void)addSections:(NSArray *)sections;
- (void)addSection:(TableViewSection *)section;
- (void)insertSection:(TableViewSection *)section atIndex:(NSInteger)index;
- (void)deleteAllSections;
- (void)deleteSectionAtIndex:(NSInteger)index;
- (void)hideSectionAtIndex:(NSInteger)index;
- (void)showSectionAtIndex:(NSInteger)index;
- (void)replaceSectionAtIndex:(NSInteger)index withSection:(TableViewSection *)section;
- (void)reloadSections;
- (void)reloadSection:(NSInteger)index;
- (id)itemForIndexPath:(NSIndexPath *)indexPath;
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UITableViewCell;

@interface TableViewDataSource (SWIFT_EXTENSION(TableAdapter)) <UITableViewDataSource>
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView;
- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section;
- (NSString *)tableView:(UITableView *)tableView titleForHeaderInSection:(NSInteger)section;
- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath;
@end

@class UIView;
@class UIScrollView;

@interface TableViewDataSource (SWIFT_EXTENSION(TableAdapter)) <UITableViewDelegate>
- (UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section;
- (UIView *)tableView:(UITableView *)tableView viewForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView heightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView heightForFooterInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForRowAtIndexPath:(NSIndexPath *)indexPath;
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForHeaderInSection:(NSInteger)section;
- (CGFloat)tableView:(UITableView *)tableView estimatedHeightForFooterInSection:(NSInteger)section;
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath;
- (void)scrollViewDidScroll:(UIScrollView *)scrollView;
@end


SWIFT_PROTOCOL("_TtP12TableAdapter27TableViewDataSourceDelegate_")
@protocol TableViewDataSourceDelegate
@optional
- (void)tableViewDidScroll:(UIScrollView *)tableView;
@end


SWIFT_CLASS("_TtC12TableAdapter16TableViewSection")
@interface TableViewSection : NSObject

/// Indicates if the receiver is hidden.
@property (nonatomic, readonly) BOOL hidden;

/// The title for the section. For book keeping purposes right now.
@property (nonatomic, copy) NSString * title;

/// The delegate for tableView methods that require an in-depth implementation.
@property (nonatomic, readonly, weak) TableViewDataSource * controller;

/// The objects to send to the cellConfigurationBlock.
@property (nonatomic, copy) NSArray * objects;

/// The number of rows in the receiver.
@property (nonatomic) NSInteger numberOfRows;
@property (nonatomic, copy) NSString * (^ cellIdentifierBlock)(id, NSIndexPath *);
@property (nonatomic, copy) void (^ cellConfigurationBlock)(UITableViewCell *, id, NSIndexPath *);
@property (nonatomic, copy) UIView * (^ headerConfigurationBlock)(NSInteger);
@property (nonatomic, copy) UIView * (^ footerConfigurationBlock)(NSInteger);
@property (nonatomic, copy) void (^ selectionBlock)(UITableViewCell *, NSIndexPath *);
- (instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithBuilder:(void (^)(TableViewSection *))builder OBJC_DESIGNATED_INITIALIZER;
- (void)addObject:(id)object;
- (void)reload;
- (void)hide;
- (void)show;
- (UITableViewCell *)cellForRow:(NSInteger)rowIndex;
@end

#pragma clang diagnostic pop
